name: ithings-doc build and deploy

on:
    push:
        branches: [master]

env:
    cache-name: ithings-admin-react

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - uses: actions/setup-node@v1
              with:
                  node-version: v16.14.0

            - name: Cache node modules
              id: cache-modules
              uses: actions/cache@v1
              env:
                  cache-name: cache-node-modules
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install dependencies
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: yarn

            - name: Build
              run: yarn build

            - name: Deploy
              uses: easingthemes/ssh-deploy@v2.2.11
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-avz --delete'
                  SOURCE: 'dist/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: /root/www
